language: c

install:
  - sudo add-apt-repository ppa:directhex/monoxide -y && sudo apt-get update
  - sudo apt-get install mono-devel mono-gmcs nunit-console
  - mozroots --import --sync

script:
  - xbuild /p:Configuration=Release source/Handlebars.sln
  - nunit-console source/Handlebars.Test/bin/Release/Handlebars.Test.dll

notifications:
  email:
    - rex@rexmorgan.net

env:
  global:
    - EnableNuGetPackageRestore=true
